### ISSUE TITLE
"Open Google" blocks other actions if placed first in a routine

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/firefox-voice#1365]
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
A routine is made that contains an "Open Google", or "Open Google.com" command (this command is placed first), then other "Open" commands. (click mic icon next to the window's menu button, click the "Settings" button from the doorhanger, click "Routines" from the left side of the "Preferences" page, click "+ New routine" button, fill out the fields with the routine name and the actions that need to be done and click the "Save" button)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the newly made routine command, e.g. "News".

### Expected result:
New tabs open corresponding to the number of routine actions that need to be made.

### Actual result:
Only the Google tab opens corresponding to the first routine action.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-23).
Not reproduced if the "Open Google"/"Open Google.com" is replaced with a "Search" or "Search Google Images" command in the routine.
Not reproduced  if the "Open Google"/"Open Google.com" is placed last in the routine. (2nd gif)
If the made routine is used multiple times, the other "Open" commands will need changing what websites to open. (see #1351)  

![4](https://user-images.githubusercontent.com/54401091/77336636-7a8adc80-6d30-11ea-9edd-cc5a66b25b4f.gif)

![5](https://user-images.githubusercontent.com/54401091/77336642-7ced3680-6d30-11ea-9a8c-5f697b218102.gif)

**Comment by dave-ok** [comment]
@ianb May I work on this?

**Comment by dave-ok** [comment]
@alexandra-martin I do not know if you test out PRs, but if you can I have created a PR #1403 that should solve this issue and probably also solve #1364 and #1351. Thanks

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 76.0a1 (2020-03-31).
Not reproduced when "Open Google" is placed first in a routine, but after the routine command is made, Google makes a search for "open".
Reproduced when "Open Google.com", "Go to Google" or "Go to Google.com" is placed first in a routine.

![7](https://user-images.githubusercontent.com/54401091/78136847-f53cb180-742c-11ea-98ed-f8461227676c.gif)

**Comment by dave-ok** [comment]
Thanks @alexandra-martin for pointing this out. @ianb I have created a separate PR #1446 that fixes this issue

**Comment by alexandra-martin** [comment]
Verified on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-14).
Unfortunately the issue is still reproducing when "open Google", "open Google.com", "go to Google", "go to Google.com" is placed first in a routine.

![7](https://user-images.githubusercontent.com/54401091/79228508-38a21180-7e6a-11ea-8890-34aa97c680eb.gif)

**Comment by dave-ok** [comment]
@ianb This issue was reintroduced by a regression in PR #1378
https://github.com/GangaChatrvedi/firefox-voice/blob/c6de989edec418a6d5d25633430f8c60651b607e/extension/background/intentRunner.js#L226-L228. 
I am guessing calling `browserUtil.loadUrl()` was in an effort to compensate for the issue that was fixed in PR #1403 , but I can't confirm this because spotify web is not available in my region yet. I think this was also mentioned in your review. I may be wrong, but I think in this case the usage was no longer necessary since the tab is already fully loaded when `browserUtils.createTab()` returns, so the onUpdated never fires in `browserUtil.loadUrl()` because the `tab.url` is unchanged.
https://github.com/dave-ok/firefox-voice/blob/b4512a023d99beb8162f2b93f080e1dc488ad4ba/extension/browserUtil.js#L86-L87  
Unless the change to `browserUtils.createTab()` introduces a regression, which seems unlikely, removing the call to `browserUtil.loadUrl()` should fix this issue. 
Can you, please, confirm this when you get the chance? Thanks

**Comment by dave-ok** [comment]
@ianb I came across issue #1526 which should also be fixed by applying the suggestion above
